apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: node-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-express
  template:
    metadata:
      labels:
        app: node-express
    spec:
      containers:
      - image: cfe84/node-express
        name: node-express
        ports:
        - containerPort: 8080
          name: node-express 
        
---

apiVersion: v1
kind: Service
metadata:
  name: node-express-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: node-express
  type: LoadBalancer